# Show help message
default:
    @just --list

# Spawn IntelliJ Community IDE in specific directory (if installed)
ide DIRECTORY:
    idea-oss {{DIRECTORY}}

# Create workspace
create-workspace:
    mkdir -p devshell
    mv flake.nix devshell

# Enter workspace
enter-workspace:
    nix develop ./devshell

# Enter workspace specifying the JDK version
enter-workspace-with-version JDK:
    nix develop ./devshell#{{JDK}}
